# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)



((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array

a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [18]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

In [19]:
# Create an array within a range of 0 and 100 with step 3
ranged_array = np.arange(0,100,3)
ranged_array


In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,size=(7,2))
random_array


In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_floats = np.random.random((3,5))
random_array_floats


In [53]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2 = np.random.randint(0,10,size=(4,6))
random_array_2


Run the cell above again, what happens? 
- The array is the same as the first time.

Are the numbers in the array different or the same? Why do think this is?
- The same, because the seed is the same and the random numbers are generated in the same order each time.

In [61]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_3 = np.random.randint(1,10,size=(3,7))
random_array_3

# Find the unique numbers in the array you just created
np.unique(random_array_3)



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# Find the 0'th index of the latest array you created
random_array_3[0]


array([6, 7, 4, 7, 8, 1, 6])

In [64]:
# Get the first 2 rows of latest array you created
random_array_3[:2]


array([[6, 7, 4, 7, 8, 1, 6],
       [8, 5, 4, 2, 6, 6, 1]])

In [65]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_3[:2,:2]

array([[6, 7],
       [8, 5]])

In [73]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_4 = np.random.randint(0,10,size=(3,5))
ones_1 = np.ones((3,5))
random_array_4,ones_1


(array([[2, 2, 3, 7, 5],
        [7, 0, 7, 3, 0],
        [7, 3, 5, 7, 3]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [74]:
# Add the two arrays together
random_array_4 + ones_1


array([[3., 3., 4., 8., 6.],
       [8., 1., 8., 4., 1.],
       [8., 4., 6., 8., 4.]])

In [75]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))
ones_2


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
# Try add the array of ones and the other most recent array together
ones_1 + ones_2


When you try the last cell, it produces an error. Why do think this is?
- Because the shape of the array is different.

How would you fix it?
- I would change the shape of the array to match the shape of the other array.


In [79]:
# Create another array of ones of shape (3, 5)
ones_3 = np.ones((3,5))


In [81]:
# Subtract the new array of ones from the other most recent array
ones_1 - ones_3


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
# Multiply the ones array with the latest array
ones_1 * ones_3


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
# Take the latest array to the power of 2 using '**'
ones_3 ** 2


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
# Do the same thing with np.square()
np.square(ones_3)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
# Find the mean of the latest array using np.mean()
np.mean(ones_3)


1.0

In [88]:
# Find the maximum of the latest array using np.max()
np.max(ones_3)


1.0

In [89]:
# Find the minimum of the latest array using np.min()
np.min(ones_3)


1.0

In [90]:
# Find the standard deviation of the latest array
np.std(ones_3)


0.0

In [91]:
# Find the variance of the latest array
np.var(ones_3)


0.0

In [92]:
# Reshape the latest array to (3, 5, 1)
ones_3.reshape((3,5,1))


array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [93]:
# Transpose the latest array
ones_3.T


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?
- It flips the array on its diagonal.


In [99]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_5 = np.random.randint(0,10,size=(3,3))
random_array_6 = np.random.randint(0,10,size=(3,2))
random_array_5,random_array_6

(array([[0, 2, 1],
        [8, 9, 5],
        [9, 2, 7]]),
 array([[7, 1],
        [5, 6],
        [1, 9]]))

In [100]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_5,random_array_6)


array([[ 11,  21],
       [106, 107],
       [ 80,  84]])

In [96]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_7 = np.random.randint(0,10,size=(4,3))
random_array_8 = np.random.randint(0,10,size=(4,3))


In [97]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_7,random_array_8)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
- I would change the shape of the first array (columns) to match the shape (rows) of the other array.

In [102]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array_7,random_array_8.T)



array([[64, 56, 28, 41],
       [34, 44,  0, 18],
       [29, 22, 20, 16],
       [65, 67, 20, 37]])

Notice how performing a transpose allows the dot product to happen.

Why is this?
- Because the shape of the arrays are now compatible for the dot product.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [110]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_9 = np.random.randint(0,10,size=(3,5))
random_array_10 = np.random.randint(0,10,size=(3,5))
random_array_9,random_array_10


(array([[3, 4, 9, 9, 4],
        [6, 3, 0, 4, 6],
        [9, 9, 5, 4, 3]]),
 array([[1, 3, 9, 9, 2],
        [9, 0, 7, 4, 3],
        [7, 6, 1, 0, 3]]))

In [111]:
# Compare the two arrays with '>'
random_array_9 > random_array_10


array([[ True,  True, False, False,  True],
       [False,  True, False, False,  True],
       [ True,  True,  True,  True, False]])

What happens when you compare the arrays with `>`?
- It returns a boolean array with the same shape as the original arrays.

In [112]:
# Compare the two arrays with '>='
random_array_9 >= random_array_10


array([[ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [114]:
# Find which elements of the first array are greater than 7
random_array_9 > 7
random_array_9[random_array_9 > 7]



array([9, 9, 9, 9])

In [116]:
# Which parts of each array are equal? (try using '==')
random_array_9 == random_array_10
random_array_9[random_array_9 == random_array_10]


array([9, 9, 4, 3])

In [117]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_9)


array([[3, 4, 4, 9, 9],
       [0, 3, 4, 6, 6],
       [3, 4, 5, 9, 9]])

In [118]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_9)


array([[0, 1, 4, 2, 3],
       [2, 1, 3, 0, 4],
       [4, 3, 2, 0, 1]], dtype=int64)

In [119]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_9)


2

In [46]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_9)


In [120]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_9,axis=1)


array([2, 0, 0], dtype=int64)

In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_9,axis=0)


In [122]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)



array([[ 1.45255025,  0.36201391,  0.58131413, -0.62970086,  0.87675465],
       [ 0.55173701, -0.71012796, -1.78767161, -1.2205701 , -0.66920273],
       [ 1.16193732,  1.55285978, -0.43951788, -0.40791535,  0.26162306]])

In [123]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.